module.exports = {
	AccountStatus: {
		NOT_FOUND: "ACCOUNT_NOT_FOUND",
		NOT_ACTIVE: "ACCOUNT_NOT_ACTIVE",
		ERROR: "ACCOUNT_REGISTER_FAILED",

		USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
		EMAIL_ALREADY_EXITS: "EMAIL_ALREADY_EXITS",
		PHONE_ALREADY_EXITS: "PHONE_NUMBER_ALREADY_EXITS",

		MISSING_USERNAME: "MISSING_USERNAME",
		MISSING_PASSWORD: "MISSING_PASSWORD",
		MISSING_FIRST_NAME: "MISSING_FIRST_NAME",
		MISSING_LAST_NAME: "MISSING_LAST_NAME",
		MISSING_EMAIL: "MISSING_EMAIL",
		MISSING_ADDRESS: "MISSING_ADDRESS",
		MISSING_PHONE: "MISSING_PHONE_NUMBER",
		MISSING_BIRTHDAY: "MISSING_BIRTHDAY",

		WRONG_PASSWORD: "ACCOUNT_WRONG_PASSWORD",
		WRONG_EMAIL_FORMAT: "EMAIL_INCORRECT_FORMAT",
	},
	ProfileStatus: {
		NOT_FOUND: "PROFILE_NOT_FOUND",
	},
	TokenStatus: {
		EXPIRED: "TOKEN_EXPIRED",
		INVALID: "TOKEN_INVALID",
		ERROR_SIGN: "TOKEN_ERROR_SIGN",
		NOT_PROVIDED: "TOKEN_NOT_PROVIDED",
		INCORRECT_FORMAT: "TOKEN_INCORRECT_FORMAT",
	},
	TokenName: {
		ACCESS: "ACCESS_TOKEN",
		REFRESH: "REFRESH_TOKEN",
	},
	TokenType: {
		ACCESS: "ACCESS_TOKEN",
		REFRESH: "REFRESH_TOKEN",
	},
	CookieStatus: {
		EXPIRED: "COOKIE_EXPIRED",
		INVALID: "COOKIE_INVALID",
		ERROR_SIGN: "COOKIE_ERROR_SIGN",
		NOT_PROVIDED: "COOKIE_NOT_PROVIDED",
		INCORRECT_FORMAT: "COOKIE_INCORRECT_FORMAT",
	},
	CartStatus: {
		NOT_FOUND: "ITEM NOT FOUND IN CART",
		ERROR_ITEM: "CART_ERROR_ITEM",
		ERROR_DELETE_ITEM: "ERROR_DELETE_ITEM_IN_CART",
		ERROR_UPDATE_QUANTITY: "ERROR_UPDATE_QUANTITY_ITEM_IN_CART",
		ERROR_ADD_TO_DATABASE: "CART_ERROR_ADD_TO_DATABASE",
	},
	ProductError: {
		ERROR_ITEM: "PRODUCT INVALID",
	},
	BillError: {
		ERROR_CREATE: "CAN'T CREATE BILL",
	},
};
